# Generated by Django 3.2.5 on 2021-08-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='check',
            field=models.IntegerField(default=0, verbose_name='Прошли тест'),
        ),
    ]
