# Generated by Django 3.2.5 on 2021-11-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_botuser_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('music_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='check',
        ),
    ]
