# Generated by Django 3.2.5 on 2021-11-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211101_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
