# Generated by Django 3.2.5 on 2021-11-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20211129_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='url',
            new_name='status',
        ),
        migrations.AddField(
            model_name='botuser',
            name='metro',
            field=models.TextField(default='0'),
        ),
    ]
