# Generated by Django 3.2.3 on 2021-11-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20211129_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.TextField(default='0')),
                ('metro', models.TextField(default='0')),
            ],
        ),
    ]
