# Generated by Django 4.0.2 on 2022-09-29 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(default='-', max_length=255)),
                ('username', models.CharField(default='-', max_length=255)),
                ('description', models.TextField(default='-')),
                ('users_count', models.IntegerField(default=0)),
                ('chat_id', models.IntegerField()),
                ('black_list', models.TextField(default='-')),
                ('white_list', models.TextField(default='-')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Названия текста')),
                ('body_ru', models.TextField(verbose_name='Русский текст')),
                ('body_eng', models.TextField(verbose_name='Английский текст')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
            },
        ),
        migrations.CreateModel(
            name='Template2Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Названия текста')),
                ('body_ru', models.TextField(verbose_name='Русский текст')),
                ('body_eng', models.TextField(verbose_name='Английский текст')),
            ],
            options={
                'verbose_name': 'Шаблон для кнопки',
                'verbose_name_plural': 'Шаблоны для кнопок',
            },
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='metro',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='paid_days',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='price',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='status',
        ),
        migrations.AddField(
            model_name='botuser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='language',
            field=models.CharField(choices=[('eng', 'eng'), ('ru', 'ru')], default='ru', max_length=5, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='chat_id',
            field=models.IntegerField(unique=True, verbose_name='Айди'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.botuser'),
        ),
    ]
