# Generated by Django 4.0.2 on 2022-09-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_botuser_km_or_kv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='km_or_kv',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='metro',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='paid_days',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='price',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='status',
        ),
    ]
