# Generated by Django 4.0.2 on 2022-09-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_botuser_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='language',
            field=models.CharField(choices=[('eng', 'eng'), ('ru', 'ru')], default='ru', max_length=5),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
