# Generated by Django 4.0.2 on 2022-09-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_rename_text_template_body_eng_template_body_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
