<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-09-29 18:50
=======
# Generated by Django 4.0.2 on 2022-09-29 18:52
>>>>>>> test

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_botuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('users_count', models.IntegerField(blank=True, null=True)),
                ('chat_id', models.IntegerField()),
                ('black_list', models.TextField(blank=True, null=True)),
                ('white_list', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
        migrations.AlterField(
            model_name='botuser',
            name='chat_id',
            field=models.IntegerField(unique=True, verbose_name='Айди'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='language',
            field=models.CharField(choices=[('eng', 'eng'), ('ru', 'ru')], default='ru', max_length=5, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='template',
            name='body_eng',
            field=models.TextField(verbose_name='Английский текст'),
        ),
        migrations.AlterField(
            model_name='template',
            name='body_ru',
            field=models.TextField(verbose_name='Русский текст'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Названия текста'),
        ),
    ]
