# Generated by Django 4.0.2 on 2022-09-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_group_alter_botuser_options_alter_template_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template2Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Названия текста')),
                ('body_ru', models.TextField(verbose_name='Русский текст')),
                ('body_eng', models.TextField(verbose_name='Английский текст')),
            ],
            options={
                'verbose_name': 'Шаблон для кнопки',
                'verbose_name_plural': 'Шаблоны для кнопок',
            },
        ),
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='group',
            name='username',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='black_list',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='users_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='white_list',
            field=models.TextField(default='-'),
        ),
    ]
