# Generated by Django 4.0.2 on 2022-09-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_group_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
    ]
