# Generated by Django 4.0.2 on 2022-09-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_group_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('Chanel', 'Канал'), ('Chat', 'Чат')], default='Chanel', max_length=255),
        ),
    ]
