# Generated by Django 4.0.2 on 2022-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='black_list_timer',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='group',
            name='white_list_timer',
            field=models.IntegerField(default=10),
        ),
    ]
