# Generated by Django 4.0.2 on 2022-10-04 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_group_black_list_timer_group_white_list_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='white_list_timer',
        ),
        migrations.AlterField(
            model_name='group',
            name='black_list',
            field=models.TextField(default='-', verbose_name='Черный список'),
        ),
        migrations.AlterField(
            model_name='group',
            name='black_list_timer',
            field=models.IntegerField(default=10, verbose_name='Таймер черного списка'),
        ),
        migrations.AlterField(
            model_name='group',
            name='chat_id',
            field=models.IntegerField(default=10, verbose_name='Чат айди'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='-', verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.CharField(default='-', max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Названия'),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('Chanel', 'Канал'), ('Chat', 'Чат')], default='Chanel', max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.botuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='group',
            name='username',
            field=models.CharField(default='-', max_length=255, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во пользователей'),
        ),
        migrations.AlterField(
            model_name='group',
            name='white_list',
            field=models.TextField(default='-', verbose_name='Белый список'),
        ),
    ]
