# Generated by Django 4.0.2 on 2022-10-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_remove_group_white_list_timer_alter_group_black_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='enable_black_list',
            field=models.BooleanField(default=False, verbose_name='Вкл/Выкл'),
        ),
        migrations.AddField(
            model_name='group',
            name='enable_white_list',
            field=models.BooleanField(default=False, verbose_name='Вкл/Выкл'),
        ),
    ]
