# Generated by Django 4.0.2 on 2022-10-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_group_enable_black_list_group_enable_white_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='enable_black_list',
            field=models.BooleanField(default=False, verbose_name='Вкл/Выкл черного список'),
        ),
        migrations.AlterField(
            model_name='group',
            name='enable_white_list',
            field=models.BooleanField(default=False, verbose_name='Вкл/Выкл белый список'),
        ),
    ]
