# Generated by Django 4.0.2 on 2022-10-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_group_enable_black_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='group_id_state',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
