# Generated by Django 3.2.3 on 2022-10-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_botuser_group_id_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='filter_document',
            field=models.BooleanField(default=True, verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='group',
            name='filter_photo',
            field=models.BooleanField(default=True, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='group',
            name='filter_text',
            field=models.BooleanField(default=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='group',
            name='filter_video',
            field=models.BooleanField(default=True, verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='group',
            name='filter_video_note',
            field=models.BooleanField(default=True, verbose_name='Кружок'),
        ),
        migrations.AddField(
            model_name='group',
            name='filter_voice',
            field=models.BooleanField(default=True, verbose_name='Голосовое'),
        ),
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='group',
            name='username',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='Никнейм'),
        ),
    ]
