# Generated by Django 3.1.6 on 2023-01-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20221031_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='filter_link_in_text',
            field=models.BooleanField(default=False, verbose_name='Ссылки скрытые в тексте'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Не трогать!!!!'),
        ),
        migrations.AlterField(
            model_name='template2button',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='template2button',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Не трогать!!!'),
        ),
    ]
